### ISSUE TITLE
import and export Method

### ISSUE THREAD

**Issue by alisharify7** [ekm507/makenote#3]
hi , in importing and exporting data from one machine to another machine, i think it's not a good method 

it's not better to add a option to script like -e or -i

example:
-- $ makenote -e[--export] location  

and app automaticlly create a csv file in path that user typed?
and in other machine using command

-- $ makenote -i[--import] location  

we can import data from csv file to db file

in more advance way we can also let users select the type of export file like : csv,txt,tsv and ...

in this method user actully can use data in other apps as well

**Comment by ekm507** [comment]
nice suggestion :+1: 
exporting to csv is a good idea. but I wonder how a csv file of several tables should look like? I mean we need one line per entry containing date and text. but we have multiple tables. how should we do this? maybe by storing data from more than one table in the same line?
so each line can look like this:
```csv
table1_date, table1_text, table2_date, table2_text, ...
```
and about importing, I agree. databases should be merged first automatically and then imported.
also it would be nice to save a backup file when doing this (while noticing the user)

thanks for the issue.

**Comment by ekm507** [comment]
would you please check latest commit of makenote?
I added import functionality.
(you need to download latest git version. it's not yet added to pip)

**Comment by alisharify7** [comment]
> nice suggestion 👍 exporting to csv is a good idea. but I wonder how a csv file of several tables should look like? I mean we need one line per entry containing date and text. but we have multiple tables. how should we do this? maybe by storing data from more than one table in the same line? so each line can look like this:
> 
> ```
> table1_date, table1_text, table2_date, table2_text, ...
> ```
> 
> and about importing, I agree. databases should be merged first automatically and then imported. also it would be nice to save a backup file when doing this (while noticing the user)
> 
> thanks for the issue.

my idea was something like:
a JSON file 

{
      "table name<notes>":[
                  "field name<id>":[1,2,3,4],
                  "field name<note>":[note1, note2, note3],
                  "field name<note date>":[date1, date2, date3],
       ] 
}

or a csv file that contain all data like:

table1id, table1note, table1date,  table2id,table2note,table2date
     1      |,   note1,      |     date1 ,|      1     |  note2,     |    date2
     2      |,   note2,      |     date2 ,|   None |  None     |    None
